//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hrModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_GZ
    {
        public string salary_standard_id { get; set; }
        public string item_name { get; set; }
        public Nullable<decimal> salary { get; set; }
        public string human_name { get; set; }
        public string human_id { get; set; }
        public string first_kind_id { get; set; }
        public string second_kind_name { get; set; }
        public string third_kind_id { get; set; }
        public string third_kind_name { get; set; }
        public string second_kind_id { get; set; }
        public string first_kind_name { get; set; }
        public string standard_id { get; set; }
        public string standard_name { get; set; }
        public short huf_id { get; set; }
    }
}
